// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package stack

import "sync"

//go:generate go run github.com/cheekybits/genny -in=$GOFILE -out=gen-$GOFILE gen "Int=int"

type IntStack struct {
	items  []int
	rwLock sync.RWMutex
}

// https://codeburst.io/slice-based-stack-implementation-in-golang-8140603a1dc2
func (stack *IntStack) Push(t int) {
	if stack.items == nil {
		stack.items = []int{}
	}
	stack.rwLock.Lock()
	stack.items = append(stack.items, t)
	stack.rwLock.Unlock()
}

func (stack *IntStack) Pop() *int {
	if len(stack.items) == 0 {
		return nil
	}
	stack.rwLock.Lock()
	item := stack.items[len(stack.items)-1]
	stack.items = stack.items[0 : len(stack.items)-1]
	stack.rwLock.Unlock()
	return &item
}

func (stack *IntStack) Size() int {
	stack.rwLock.RLock()
	defer stack.rwLock.RUnlock()
	return len(stack.items)
}

func (stack *IntStack) All() []int {
	stack.rwLock.RLock()
	defer stack.rwLock.RUnlock()
	return stack.items
}

func (stack *IntStack) IsEmpty() bool {
	stack.rwLock.RLock()
	defer stack.rwLock.RUnlock()
	return len(stack.items) == 0
}
